//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exemple_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int ID { get; set; }
        public string NOM_CILENT { get; set; }
        public string ADRESSE { get; set; }
        public string TYPE_CLIENT { get; set; }
        public Nullable<int> ICE { get; set; }
    }
}
